### ISSUE TITLE
上传文件的验证问题

### ISSUE THREAD

**Issue by 15237179193** [wen-gg/webman-laravel-validate#1]
验证规则如下：
public function rules()
    {
        return [
            'user_excel' => 'required|file',
        ];
    }
提示：必须是文件，怀疑webman接收文件的对象和laravel接受文件的对象实例不一样导致的，能否解决一下？

**Comment by wen-gg** [comment]
这种情况可根据laravel自定义验证规则自行扩展一个 file 验证，不建议改动原包file验证
